

language: generic

sudo: required



services:
  - docker

 before_install:
  - docker build -t rakesh12z/docker-react -f dockerfile.dev .


script:
 - docker run -e CI=true rakesh12z/docker-react npm run test -- --coverage