

sudo: required

language: node_js

node_js:
 - "8"

services:
 - docker

before_install:
 - docker build -t vovikdevop/docker-react -f Dockerfile.dev .

script: 
 - docker run vovikdevop/docker-react npm run test -- --coverage

