

sudo: required

language: node_js

node_js:
 - "8"

services:
 - docker

before_install:
 - docker build -t rakeshz12/docker-react -f Dockerfile.dev .

script: 
 - docker run -e CI=true rakeshz12/react-app npm run test -- --coverage

