 sudo: required
 language: GENERIC

services:
 - docker

before_install:
 - docker build -t rakeshz12/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true rakeshz12/docker-react npm run test -- --coverage




 deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "Docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-745833700570"
  bucket_path: "Docker-react"
  on:
    branch: origin
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
