language: generic 

sudo: required 

services:
  - docker

 before_install:
  - docker build -t rakeshz12/docker-react -f dockerfile.dev .


script:
 - docker run -e CI=true rakeshz12/docker-react npm run test -- --coverage